# Generated by Django 5.2.5 on 2026-04-29 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RunSQL(
            sql=[
                # Drop FK constraints that reference users_user.id
                "ALTER TABLE users_user_groups DROP CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id;",
                "ALTER TABLE users_user_user_permissions DROP CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id;",
                "ALTER TABLE django_admin_log DROP CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id;",
                "ALTER TABLE reservations_reservation DROP CONSTRAINT reservations_reservation_user_id_6ed5b1c9_fk_users_user_id;",
                # Swap the PK column
                "ALTER TABLE users_user DROP CONSTRAINT users_user_pkey;",
                "ALTER TABLE users_user DROP COLUMN id;",
                "ALTER TABLE users_user ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();",
                # Also change the FK columns in related tables to uuid and recreate constraints
                "ALTER TABLE users_user_groups DROP COLUMN user_id;",
                "ALTER TABLE users_user_groups ADD COLUMN user_id uuid NOT NULL REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED;",
                "ALTER TABLE users_user_user_permissions DROP COLUMN user_id;",
                "ALTER TABLE users_user_user_permissions ADD COLUMN user_id uuid NOT NULL REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED;",
                "ALTER TABLE django_admin_log DROP COLUMN user_id;",
                "ALTER TABLE django_admin_log ADD COLUMN user_id uuid NOT NULL REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED;",
                "ALTER TABLE reservations_reservation DROP COLUMN user_id;",
                "ALTER TABLE reservations_reservation ADD COLUMN user_id uuid NOT NULL REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED;",
            ],
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
