# Generated by Django 6.0.4 on 2026-04-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='timezone',
        ),
    ]
