# Generated by Django 5.2.5 on 2026-04-29 19:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_building_timezone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'is_active'], name='room_building_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='building_name_unique_ci'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), models.F('building'), name='room_name_building_unique_ci'),
        ),
    ]
