# Generated by Django 5.2.5 on 2026-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_room_building_active_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['name'], name='building_name_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'name'], name='room_building_name_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='room_name_idx'),
        ),
    ]
