# Generated by Django 5.2.5 on 2026-04-29 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
        ('rooms', '0003_room_room_building_active_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'status', 'start_time', 'end_time'], name='reservation_overlap_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'start_time'], name='reservation_user_time_idx'),
        ),
    ]
